spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/prueba
    username: root
    password: Hola
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true