spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/prueba
    username: root
    password: Hola
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

swagger:
  project:
    name: Gestion de Usuarios Nataly
    description: Backend microservicio de prueba
    version: 1.0
    contactName: COEXITO
    contactEmail: email@coexito.com